package de.akquinet.ccsp.monitoring.jdbc.wrapper

import de.akquinet.ccsp.monitoring.*
import java.sql.Connection
import java.sql.SQLException

class JDBCConnection(
	private val jdbcMetrics: JDBCMetrics,
	private val connection: Connection
) : Connection by connection {
	@Throws(SQLException::class)
	override fun close() {
		jdbcMetrics.counter(JDBC_CONNECTIONS_CLOSED).increment()
		jdbcMetrics.gaugeCounter(JDBC_CONNECTIONS_ACTIVE).decrement()
		connection.close()
	}

	@Throws(SQLException::class)
	override fun prepareStatement(sql: String) =
		JDBCPreparedStatement(jdbcMetrics, sql, connection.prepareStatement(sql))

	@Throws(SQLException::class)
	override fun prepareStatement(sql: String, autoGeneratedKeys: Int) =
		JDBCPreparedStatement(jdbcMetrics, sql, connection.prepareStatement(sql, autoGeneratedKeys))

	@Throws(SQLException::class)
	override fun prepareStatement(sql: String, columnIndexes: IntArray) =
		JDBCPreparedStatement(jdbcMetrics, sql, connection.prepareStatement(sql, columnIndexes))

	@Throws(SQLException::class)
	override fun prepareStatement(sql: String, columnNames: Array<String>) =
		JDBCPreparedStatement(jdbcMetrics, sql, connection.prepareStatement(sql, columnNames))

	@Throws(SQLException::class)
	override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int) =
		JDBCPreparedStatement(jdbcMetrics, sql, connection.prepareStatement(sql, resultSetType, resultSetConcurrency))

	@Throws(SQLException::class)
	override fun prepareStatement(
		sql: String,
		resultSetType: Int,
		resultSetConcurrency: Int,
		resultSetHoldability: Int
	) = JDBCPreparedStatement(
		jdbcMetrics, sql, connection.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
	)
}